#!/bin/sh
alias ka="killall" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	g="git" \
	e="$EDITOR" \
	vm="$EDITOR -S main.vim --servername "main"" \
	vc="$EDITOR -S coding.vim --servername "coding"" \
	vl="vim --serverlist" \
	x="sxiv -ft *" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	l="ls -l" \
	la="ls -a" \
	lla="ls -la" \
	duns="waltemplates.sh" \
	Spr="source ~/.profile" \
	ls="ls --color=auto" \
	reflect="sudo reflector --age 8 --fastest 128 --latest 64 --number 32 --sort rate --save /etc/pacman.d/mirrorlist"\
	dettach="</dev/null &>/dev/null &" \
	wall="cd /home/niko/Images/wall &&  fzfimg --bind 'enter:execute-silent(wal -i {} -st)'"

# TaskWarrior Aliases & Functions

function taskProjects() {
	task project:$1
}

alias	t="task"\
	tw="ls ~/.task/*.data | entr -d task"\
	tday="task burndown.daily && echo ~/.task/backlog.data | entr -d task burndown.daily"\
	tp="taskProjects"\
	tpl="task projects"\
	tl="task list"\
	tnw="task newest"\ 
# command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
#vf() { fzf | xargs -r -I % $EDITOR % ;}
